version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: .env
    container_name: postgres_laliga
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - ./:/app
        - /app/node_modules
      depends_on:
        - db
      ports:
        - "8080:8080"

volumes:
  postgres_data: